AllCops:
  TargetRubyVersion: 2.3

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/DoubleNegation:
  Enabled: false

Performance/RedundantBlockCall:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Metrics/ClassLength:
  Max: 250

Metrics/LineLength:
  Max: 99
  Exclude:
    - spec/zombie_killer_spec.rb

# Offense count: 2
Metrics/AbcSize:
  Max: 23

# Offense count: 1
Metrics/CyclomaticComplexity:
  Max: 11

# Offense count: 4
Metrics/MethodLength:
  Max: 21

# Offense count: 1
Metrics/PerceivedComplexity:
  Max: 10

