AllCops:
  TargetRubyVersion: 2.3

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/DoubleNegation:
  Enabled: false

Performance/RedundantBlockCall:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Metrics/ClassLength:
  Max: 250

Metrics/LineLength:
  Max: 99

#inherit_from: .rubocop_todo.yml

