#! /usr/bin/env ruby
# frozen_string_literal: true

# Usage: all_zombie_counter [FILES]
#   if no FILES are given, finds all *.rb files under CWD
require "parallel"
require "pp"
require_relative "../lib/zombie_killer/code_histogram"

filenames = ARGV
filenames = `find -name "*.rb"`.split "\n" if filenames.empty?

RUBY_REWRITE = "ruby-rewrite2.0"
ONE_ZOMBIE_COUNTER = "ops_add_counter.rb"
# @returns [Array] lines
def count_zombies_in_file(filename)
  cmd = "#{RUBY_REWRITE} 2>&1 >/dev/null -l #{ONE_ZOMBIE_COUNTER} #{filename}"
  `#{cmd}`.lines
end

NPROC = `nproc`.chomp.to_i
histograms = Parallel.map(filenames, in_threads: NPROC) do |fn|
  CodeHistogram.parse_by_frequency(count_zombies_in_file(fn))
end

total = histograms.each_with_object(CodeHistogram.new) do |obj, memo|
  memo.merge! obj
end
total.print_by_frequency($stdout)
